version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src # ソースコードをマウント
      - ./resources:/app/resources # リソースもマウント
      - ~/.m2:/root/.m2 # ローカルの Maven リポジトリをマウント（依存関係をキャッシュ）

  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: "Asia/Tokyo"
    volumes:
      - ./conf:/etc/mysql/conf.d
      - db_data:/var/lib/mysql

volumes:
  db_data:
